CREATE DATABASE IF NOT EXISTS 436db;

USE 436db;

CREATE TABLE IF NOT EXISTS users (
  screenname VARCHAR(50) PRIMARY KEY,
  login_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
  x_player VARCHAR(50),
  o_player VARCHAR(50)
);
